name: Main workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v1

      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Code Analysis
        run: ./gradlew ktlintCheck --no-daemon

      - name: Assemble and Test
        run: ./gradlew build --no-daemon